### PR TITLE
Fix a bunch of dependencies

### LINKED ISSUE #333: Unable to run the site locally with node 6.10.2
I don't know if this is related to #332 but I cannot get SW to run locally either. `npm start` gives a bunch of scary looking C stack traces from the v8 javascript engine.
```
==== C stack trace ===============================

 1: v8::Template::Set(v8::Local<v8::Name>, v8::Local<v8::Data>, v8::PropertyAttribute)
 2: fse::FSEvents::Initialize(v8::Local<v8::Object>)
 3: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&)
 4: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&))
 5: v8::internal::(anonymous namespace)::HandleApiCallHelper(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)3>)
 6: v8::internal::Builtin_Impl_HandleApiCall(v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)3>, v8::internal::Isolate*)
 7: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*)
 8: 0x1288111092a7
 9: 0x1288117be944
10: 0x128811508718
```
node: 6.10.2
npm: 3.10.10
OS: OSX 10.11.6

### PR DESCRIPTION
**Pull request by simoneduca**
Fixes #333.

However, I have no idea why removing the call to the `clean` task was necessary to run the app.

@rogerhutchings, it's a long shot, but any thoughts?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
I don't know if this makes a serious difference to npm, but all of the dependencies in `package.json` are listed as dev dependencies.

**Comment by simoneduca** [comment]
Mm, I think it's always been like that and now I understand that  ideally it shouldn't have been. If anything what would it make a difference to?

**Comment by eatyourgreens** [comment]
It would make a difference if we had automated builds in a production environment.
>With the --production flag (or when the NODE_ENV environment variable is set to production), npm will not install modules listed in devDependencies.
https://docs.npmjs.com/cli/install

**Comment by simoneduca** [comment]
I see, thanks. Can you run the app locally?

**Comment by eatyourgreens** [comment]
No, see my comments on #333 All I get is a blank grey page in the browser.

**Comment by simoneduca** [comment]
OK,I'll open a separate issue about devDependencies, since it doesn't seem relevant for this PR.

**Comment by simoneduca** [comment]
The last change is because [`0.1.17` breaks everything](https://github.com/fshost/node-dir/issues/50).

**Comment by simoneduca** [comment]
LGTM. Thanks @eatyourgreens 👍

**Pull request merged**
