### PR TITLE
pdfs not producing properly in Firefox

### PR DESCRIPTION
**Pull request by rogerhutchings**
The text is cut off for some reason. 
screen shot 2015-11-05 at 11 32 03

### CODE REVIEW

**Comment by rogerhutchings** [comment]
Not sure why we're doing this on the client - different browsers are always going to produce different results, with Chrome rendering lines a lot wider than other browsers, as it turns out. But this should work for everything.

Note that it's now using Courier (a monospaced font) for the text, as there's no other way to guarantee a consistent line length.

**Comment by VVH** [comment]
Hey @simoneduca and @rogerhutchings a user on Talk just commented that pdfs only seem to be saving/outputting one line. Is it possible the pdf isn't grabbing all the lines, or that the rest is there, but has been cut off?

**Comment by rogerhutchings** [comment]
A fix is already in, it just needs to be reviewed before we deploy it

**Comment by simoneduca** [comment]
tested and deployed

**Pull request merged**
