### PR TITLE
Remove ! from routes and change transcribe routes

### LINKED ISSUE #372: Classify link on Talk has the wrong fragment ID
[SW Talk](https://www.zooniverse.org/projects/zooniverse/shakespeares-world/talk/) uses the standard project navigation, so the classify link links to https://www.shakespearesworld.org/#/classify

Is it possible to alias the `#/classify` fragment identifier so that it loads the transcribe view, or redirects to `#/transcribe`?

### PR DESCRIPTION
**Pull request by simoneduca**
Fix #372 

I'm not sure if theroutes need to be updated server-side as well, but this takes care of the frontend.

### CODE REVIEW

**Comment by simoneduca** [comment]
It does.

**Comment by simoneduca** [comment]
https://preview.zooniverse.org/shakespearesworld/#!/

**Comment by eatyourgreens** [comment]
Can `/classify` redirect to `/transcribe` as per #372 or doesn’t Angular allow that?

**Comment by eatyourgreens** [comment]
Also, this changes the link to `#!/classify` but the link from the Talk page goes to `#/classify` (no exclamation mark.)

**Comment by simoneduca** [comment]
Regarding redirecting I'm not, I'll check. The link from the Talk doesn't work because of the missing `!`. `#/classify` is hardcoded in PFE, so I assume it would break all other projects if we added a `!`.

**Comment by simoneduca** [comment]
I've found the correct way of getting rid of the hash-bang `#!`. [Here's some info about when it was introduced](https://docs.angularjs.org/guide/migration#commit-aa077e8)
I've tested two ways we could handle this:

1. `$locationProvider.hashPrefix('');` gets rid of just `!`
2. `$locationProvider.html5Mode(true);` gets rid of `#!`

2. is my favourite as it's easier to share and read. However, PFE links have `#` hardcoded in, so I'm worried that could break SW nav when redirected there from PFE.

Any thoughts @eatyourgreens?

**Comment by eatyourgreens** [comment]
For option 2, you’ll also need to configure the server to resolve URLs like https://www.shakespearesworld.org/classify back to https://www.shakespearesworld.org/index.html You can ask on Slack if you need help with that.

**Comment by simoneduca** [comment]
I went with option 1 https://preview.zooniverse.org/shakespearesworld/#/. Regarding the redirect, I'm not sure how to do it/if it's possible. What would the benefit be? Bookmarked links?

**Comment by eatyourgreens** [comment]
http://isolani.co.uk/blog/javascript/BreakingTheWebWithHashBangs

**Comment by simoneduca** [comment]
Nice and useful article, thanks.

**Comment by eatyourgreens** [comment]
Should I merge this? It looks good to me.

**Comment by simoneduca** [comment]
Sorry @eatyourgreens, yes please!

**Pull request merged**
