### PR TITLE
Implement OAuth module

### LINKED ISSUE #286: Upgrade panoptes-javascript-client to use the new OAuth library
Once zooniverse/panoptes-javascript-client#24 is merged, we can use the new OAuth library. This automatically refreshes bearer tokens, fixing #272 and #227 

This means modifying [auth.factory.js](https://github.com/zooniverse/shakespeares_world/blob/master/app/modules/auth/auth.factory.js) to use the `oauth` methods `checkCurrent`, `signIn` and `signOut`, and store the user object as it currently does. These work identically to those in the existing `auth` module.

It should also run the OAuth `init` method in the `app.module.js` file, and run `startApp` as a function after that promise resolves

### PR DESCRIPTION
**Pull request by rogerhutchings**
This PR bumps the `panoptes-client` version, and rewrites the auth factory to use the new OAuth module.

To test this locally, this now needs the `?env=production` parameter set in the URL, so it now looks like `http://localhost:3001/?env=production#/`. It should work fine when deployed, as the environment is set to `production` in the gulp task.

I'm going to deploy it to staging now for testing there as well. 

Fix #286

### CODE REVIEW

**Comment by rogerhutchings** [comment]
screen shot 2016-04-14 at 15 02 37

weirdness on logout... only on staging though :/

**Comment by camallen** [comment]
@rogerhutchings production won't allow localhost or any non *.zooniverse.org cors requests.

**Comment by rogerhutchings** [comment]
TIL

**Comment by camallen** [comment]
may not still work on custom domains, we'll have to add them to the whitelist.

**Comment by rogerhutchings** [comment]
@shaunanoordin okay, i think this is ready to be tested now. please note the change in the readme - there's no staging app in panoptes, so you can test auth locally, but the app itself won't work locally.

**Comment by camallen** [comment]
@rogerhutchings it will work if you deploy it to sw-preview.zooniverse.org or something of the like.

**Comment by rogerhutchings** [comment]
yeah, there's a `deploy-staging` npm command to deploy it to http://preview.zooniverse.org/shakespearesworld

**Comment by shaunanoordin** [comment]
Currently, we are investigating an issue with the login.

Issue: A user with *no avatar* cannot log in to the app. The app will not recognise that a valid user has successfully logged in via Panoptes.
Setup: `oauth` branch is deployed (via `npm run deploy-staging` to preview.zooniverse.org/shakespearesworld ; various user accounts were used to log in.

Analysis:
Let's take a look at `app/modules/auth/auth.factory.js`, in the `_setUserData()` function.
```
function _setUserData() {
    return zooAPI.type('me').get()
        .then(function (response) {
            var response = response[0];
            _user.id = response.id;
            _user.display_name = response.display_name;
            alert('FLAG 1');
            return response.get('avatar');
        })
        .then(function (response) {
            alert('FLAG 2');
            var response = response[0];
            _user.avatar = (response.src) ? response.src : null;
            $rootScope.$broadcast('auth:loginChange', _user);
            return _user;
        })
        .then(CribsheetFactory.$getData)
        .catch(function (error) {
            console.error('somethings wrong', error)
        });
}
```
If a user has **successfully** logged in via Panoptes but does **not** have an avatar in her/his profile, then we'll reach FLAG 1 but not FLAG 2. Specifically, at FLAG 1, the app correctly gets `_user.id` and `_user.display_name` but `return response.get('avatar');` causes the whole Promise chain to die.

As Roger points it, it's likely that the returned Promise simply rejects instead of returning null, and an extra catch block should be able to stop this bug from occuring.

Status: **Investigating**

Tested on Chrome49/FF45 on OSX+MacbookPro.

**Comment by shaunanoordin** [comment]
Awright, LGTM!

* Branch deployed to https://preview.zooniverse.org/shakespearesworld/ for testing.
* Non-logged in users can access the website, transcribe pages and login normally.
* Logged in users can access the website, transcribe pages and logout normally.
* App works normally whether or not the logged in user has an avatar.
* Code changes looks legit.

Tested on Chrome50/Firefox45/Safari9 on OSX+MacbookPro

Status: **Verified**
Action: **Merging**

**Pull request merged**
