### PR TITLE
Add dockerfile

### PR DESCRIPTION
**Pull request by rogerhutchings**
Builds to `/usr/src/app/build`

### CODE REVIEW

**Comment by simoneduca** [comment]
@astopy comma removed.

**Comment by simoneduca** [comment]
Odd, I'll have a look, thanks.

**Comment by simoneduca** [comment]
I'm trying to get the full error back by[ using pump for gulp as recommended](https://github.com/terinjokes/gulp-uglify/blob/master/docs/why-use-pump/README.md#using-pump).

**Comment by simoneduca** [comment]
So, having 
```
         return stream.on('error', function() {
            pump([
                source(file),
                gulpif(createSourcemap, buffer()),
                gulpif(createSourcemap, sourcemaps.init()),
                gulpif(global.isProd, streamify(uglify({
                    compress: { drop_console: true }
                }))),
                gulpif(createSourcemap, sourcemaps.write('./')),
                gulp.dest(config.scripts.dest),
                gulpif(browserSync.active, browserSync.reload({ stream: true, once: true }))
                ],
                handleErrors
            )
        })
```
instead of https://github.com/zooniverse/shakespeares_world/blob/master/gulp/tasks/browserify.js#L62-L72
seems to get rid of the error, but I have no idea why.
On the other hand, it doesn't seem to bundle things correctly, as you can't see the app in the browser. @rogerhutchings any thoughts?

**Comment by rogerhutchings** [comment]
I've made a tiny change to one of the gulp files. I then tested the new image by building it, copying the contents of the `/usr/app/src/build` to the host, and running the built app. It works for me, but would someone mind trying it again?

**Comment by rogerhutchings** [comment]
oh wait I just saw the command you're running @astopy - i'll try testing it with that too

**Comment by rogerhutchings** [comment]
Right, it should be fixed - all down to node 4 choking on a backticked string, so I changed it to a single-quoted string (the `\`s escape the newline characters) and managed to successfully build and deploy to staging.

@astopy, would you mind testing the docker image again?

**Comment by simoneduca** [comment]
Just a thought, since SW works with latest node why don't we specify that inside `engines`?

**Comment by eatyourgreens** [comment]
Out of interest, why not use a more recent version of node?

**Comment by simoneduca** [comment]
Great minds

**Comment by rogerhutchings** [comment]
I thought Cam tried building it yesterday and it broke. Will experiment though

**Comment by simoneduca** [comment]
I could build it no problem with 8.8.1, that was the whole point of a bunch of upgrade I made a while ago.

**Comment by simoneduca** [comment]
Btw, both `deploy-staging` and `start` commands working fine here.

**Comment by rogerhutchings** [comment]
Right. Node version is bumped to 9, but I've found out that it's actually gulp-uglify that can't handle es6 features like backticked strings, so I'm still using them here. Everything looks like it's working now.

**Comment by astopy** [comment]
I've set up an automated build on Docker Hub https://hub.docker.com/r/zooniverse/shakespeares_world/builds/

**Comment by astopy** [comment]
Let me know if you also want me to hook this up to Jenkins

**Comment by rogerhutchings** [comment]
Hi @astopy - would you mind doing the Jenkins hookup? I'm going to do a manual deploy for now so we can turn off the old aggregation code

**Comment by astopy** [comment]
Done!

**Pull request merged**
